apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/cloudserver-250320/edgefs:{{.VERSION}}'
  local: {}
  cluster:
    timeout: 2h
    resources:
      requests:
        cpu: 8
        memory: 16Gi
      limits:
        cpu: 12
        memory: 32Gi
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/cloudserver-250320/edgefs:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: edgefs
        chartPath: charts/edgefs
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/cloudserver-250320/edgefs'
          image.tag: '{{.DIGEST_HEX}}'
