AC_CONFIG_FILES([
	src/libreptrans/rtlfs/Makefile
	src/libreptrans/rtrd/Makefile
	src/libreptrans/rtkvs/Makefile
	src/libreptrans/rtkvs/backend/kvsfs/Makefile
	src/libreptrans/rtkvs/backend/kvslmdb/Makefile
	src/libreptrans/rtkvs/backend/kvssd/Makefile
	src/libreptrans/Makefile
])
