// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system.proto

package system

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenericRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericRequest) Reset()         { *m = GenericRequest{} }
func (m *GenericRequest) String() string { return proto.CompactTextString(m) }
func (*GenericRequest) ProtoMessage()    {}
func (*GenericRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{0}
}

func (m *GenericRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericRequest.Unmarshal(m, b)
}
func (m *GenericRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericRequest.Marshal(b, m, deterministic)
}
func (m *GenericRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericRequest.Merge(m, src)
}
func (m *GenericRequest) XXX_Size() int {
	return xxx_messageInfo_GenericRequest.Size(m)
}
func (m *GenericRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenericRequest proto.InternalMessageInfo

type VdevInfo struct {
	DevName              string   `protobuf:"bytes,1,opt,name=devName,proto3" json:"devName,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Capacity             int64    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Used                 int64    `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	Util                 int64    `protobuf:"varint,5,opt,name=util,proto3" json:"util,omitempty"`
	Mdutil               int64    `protobuf:"varint,6,opt,name=mdutil,proto3" json:"mdutil,omitempty"`
	S3Util               int64    `protobuf:"varint,7,opt,name=s3util,proto3" json:"s3util,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VdevInfo) Reset()         { *m = VdevInfo{} }
func (m *VdevInfo) String() string { return proto.CompactTextString(m) }
func (*VdevInfo) ProtoMessage()    {}
func (*VdevInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{1}
}

func (m *VdevInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VdevInfo.Unmarshal(m, b)
}
func (m *VdevInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VdevInfo.Marshal(b, m, deterministic)
}
func (m *VdevInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VdevInfo.Merge(m, src)
}
func (m *VdevInfo) XXX_Size() int {
	return xxx_messageInfo_VdevInfo.Size(m)
}
func (m *VdevInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VdevInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VdevInfo proto.InternalMessageInfo

func (m *VdevInfo) GetDevName() string {
	if m != nil {
		return m.DevName
	}
	return ""
}

func (m *VdevInfo) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *VdevInfo) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *VdevInfo) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *VdevInfo) GetUtil() int64 {
	if m != nil {
		return m.Util
	}
	return 0
}

func (m *VdevInfo) GetMdutil() int64 {
	if m != nil {
		return m.Mdutil
	}
	return 0
}

func (m *VdevInfo) GetS3Util() int64 {
	if m != nil {
		return m.S3Util
	}
	return 0
}

type SystemInfo struct {
	HostName             string               `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	ContId               string               `protobuf:"bytes,2,opt,name=contId,proto3" json:"contId,omitempty"`
	Gw                   bool                 `protobuf:"varint,3,opt,name=gw,proto3" json:"gw,omitempty"`
	State                string               `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	VdevCount            int32                `protobuf:"varint,5,opt,name=vdevCount,proto3" json:"vdevCount,omitempty"`
	VdevOfflineCount     int32                `protobuf:"varint,6,opt,name=vdevOfflineCount,proto3" json:"vdevOfflineCount,omitempty"`
	VdevReadOnlyCount    int32                `protobuf:"varint,7,opt,name=vdevReadOnlyCount,proto3" json:"vdevReadOnlyCount,omitempty"`
	Vdevs                map[string]*VdevInfo `protobuf:"bytes,8,rep,name=vdevs,proto3" json:"vdevs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SystemInfo) Reset()         { *m = SystemInfo{} }
func (m *SystemInfo) String() string { return proto.CompactTextString(m) }
func (*SystemInfo) ProtoMessage()    {}
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{2}
}

func (m *SystemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfo.Unmarshal(m, b)
}
func (m *SystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfo.Marshal(b, m, deterministic)
}
func (m *SystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfo.Merge(m, src)
}
func (m *SystemInfo) XXX_Size() int {
	return xxx_messageInfo_SystemInfo.Size(m)
}
func (m *SystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfo proto.InternalMessageInfo

func (m *SystemInfo) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *SystemInfo) GetContId() string {
	if m != nil {
		return m.ContId
	}
	return ""
}

func (m *SystemInfo) GetGw() bool {
	if m != nil {
		return m.Gw
	}
	return false
}

func (m *SystemInfo) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SystemInfo) GetVdevCount() int32 {
	if m != nil {
		return m.VdevCount
	}
	return 0
}

func (m *SystemInfo) GetVdevOfflineCount() int32 {
	if m != nil {
		return m.VdevOfflineCount
	}
	return 0
}

func (m *SystemInfo) GetVdevReadOnlyCount() int32 {
	if m != nil {
		return m.VdevReadOnlyCount
	}
	return 0
}

func (m *SystemInfo) GetVdevs() map[string]*VdevInfo {
	if m != nil {
		return m.Vdevs
	}
	return nil
}

type SystemStatusResponse struct {
	Status               map[string]*SystemInfo `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SystemStatusResponse) Reset()         { *m = SystemStatusResponse{} }
func (m *SystemStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SystemStatusResponse) ProtoMessage()    {}
func (*SystemStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{3}
}

func (m *SystemStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemStatusResponse.Unmarshal(m, b)
}
func (m *SystemStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemStatusResponse.Marshal(b, m, deterministic)
}
func (m *SystemStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemStatusResponse.Merge(m, src)
}
func (m *SystemStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SystemStatusResponse.Size(m)
}
func (m *SystemStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SystemStatusResponse proto.InternalMessageInfo

func (m *SystemStatusResponse) GetStatus() map[string]*SystemInfo {
	if m != nil {
		return m.Status
	}
	return nil
}

type SystemSummaryResponse struct {
	TotalCapacity          int64    `protobuf:"varint,1,opt,name=totalCapacity,proto3" json:"totalCapacity,omitempty"`
	TotalUsed              int64    `protobuf:"varint,2,opt,name=totalUsed,proto3" json:"totalUsed,omitempty"`
	TotalAvailable         int64    `protobuf:"varint,3,opt,name=totalAvailable,proto3" json:"totalAvailable,omitempty"`
	TotalUtilization       float32  `protobuf:"fixed32,4,opt,name=totalUtilization,proto3" json:"totalUtilization,omitempty"`
	TotalMdoffloadCapacity int64    `protobuf:"varint,5,opt,name=totalMdoffloadCapacity,proto3" json:"totalMdoffloadCapacity,omitempty"`
	TotalMdoffloadUsed     int64    `protobuf:"varint,6,opt,name=totalMdoffloadUsed,proto3" json:"totalMdoffloadUsed,omitempty"`
	TotalS3OffloadCapacity int64    `protobuf:"varint,7,opt,name=totalS3offloadCapacity,proto3" json:"totalS3offloadCapacity,omitempty"`
	TotalS3OffloadUsed     int64    `protobuf:"varint,8,opt,name=totalS3offloadUsed,proto3" json:"totalS3offloadUsed,omitempty"`
	TotalVersions          int64    `protobuf:"varint,9,opt,name=totalVersions,proto3" json:"totalVersions,omitempty"`
	TrlogMarker            int64    `protobuf:"varint,10,opt,name=trlogMarker,proto3" json:"trlogMarker,omitempty"`
	TrlogMarkerDelay       int64    `protobuf:"varint,11,opt,name=trlogMarkerDelay,proto3" json:"trlogMarkerDelay,omitempty"`
	Guid                   string   `protobuf:"bytes,12,opt,name=guid,proto3" json:"guid,omitempty"`
	Segid                  string   `protobuf:"bytes,13,opt,name=segid,proto3" json:"segid,omitempty"`
	Timezone               string   `protobuf:"bytes,14,opt,name=timezone,proto3" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *SystemSummaryResponse) Reset()         { *m = SystemSummaryResponse{} }
func (m *SystemSummaryResponse) String() string { return proto.CompactTextString(m) }
func (*SystemSummaryResponse) ProtoMessage()    {}
func (*SystemSummaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{4}
}

func (m *SystemSummaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemSummaryResponse.Unmarshal(m, b)
}
func (m *SystemSummaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemSummaryResponse.Marshal(b, m, deterministic)
}
func (m *SystemSummaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemSummaryResponse.Merge(m, src)
}
func (m *SystemSummaryResponse) XXX_Size() int {
	return xxx_messageInfo_SystemSummaryResponse.Size(m)
}
func (m *SystemSummaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemSummaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SystemSummaryResponse proto.InternalMessageInfo

func (m *SystemSummaryResponse) GetTotalCapacity() int64 {
	if m != nil {
		return m.TotalCapacity
	}
	return 0
}

func (m *SystemSummaryResponse) GetTotalUsed() int64 {
	if m != nil {
		return m.TotalUsed
	}
	return 0
}

func (m *SystemSummaryResponse) GetTotalAvailable() int64 {
	if m != nil {
		return m.TotalAvailable
	}
	return 0
}

func (m *SystemSummaryResponse) GetTotalUtilization() float32 {
	if m != nil {
		return m.TotalUtilization
	}
	return 0
}

func (m *SystemSummaryResponse) GetTotalMdoffloadCapacity() int64 {
	if m != nil {
		return m.TotalMdoffloadCapacity
	}
	return 0
}

func (m *SystemSummaryResponse) GetTotalMdoffloadUsed() int64 {
	if m != nil {
		return m.TotalMdoffloadUsed
	}
	return 0
}

func (m *SystemSummaryResponse) GetTotalS3OffloadCapacity() int64 {
	if m != nil {
		return m.TotalS3OffloadCapacity
	}
	return 0
}

func (m *SystemSummaryResponse) GetTotalS3OffloadUsed() int64 {
	if m != nil {
		return m.TotalS3OffloadUsed
	}
	return 0
}

func (m *SystemSummaryResponse) GetTotalVersions() int64 {
	if m != nil {
		return m.TotalVersions
	}
	return 0
}

func (m *SystemSummaryResponse) GetTrlogMarker() int64 {
	if m != nil {
		return m.TrlogMarker
	}
	return 0
}

func (m *SystemSummaryResponse) GetTrlogMarkerDelay() int64 {
	if m != nil {
		return m.TrlogMarkerDelay
	}
	return 0
}

func (m *SystemSummaryResponse) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *SystemSummaryResponse) GetSegid() string {
	if m != nil {
		return m.Segid
	}
	return ""
}

func (m *SystemSummaryResponse) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func init() {
	proto.RegisterType((*GenericRequest)(nil), "system.GenericRequest")
	proto.RegisterType((*VdevInfo)(nil), "system.VdevInfo")
	proto.RegisterType((*SystemInfo)(nil), "system.SystemInfo")
	proto.RegisterMapType((map[string]*VdevInfo)(nil), "system.SystemInfo.VdevsEntry")
	proto.RegisterType((*SystemStatusResponse)(nil), "system.SystemStatusResponse")
	proto.RegisterMapType((map[string]*SystemInfo)(nil), "system.SystemStatusResponse.StatusEntry")
	proto.RegisterType((*SystemSummaryResponse)(nil), "system.SystemSummaryResponse")
}

func init() { proto.RegisterFile("system.proto", fileDescriptor_86a7260ebdc12f47) }

var fileDescriptor_86a7260ebdc12f47 = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0x6b, 0x27, 0x71, 0xd2, 0x93, 0x36, 0x64, 0xa2, 0x2b, 0x22, 0x74, 0x10, 0xc2, 0x28,
	0x61, 0x8c, 0x5c, 0x34, 0x30, 0xc6, 0xae, 0x36, 0xba, 0x7f, 0x1d, 0x74, 0x05, 0x97, 0xf5, 0x5e,
	0x8d, 0x95, 0x4c, 0x54, 0xb1, 0x3a, 0x4b, 0x4e, 0x71, 0x1f, 0x65, 0x2f, 0xb0, 0xbb, 0xdd, 0xef,
	0x69, 0xf6, 0x2a, 0x43, 0x47, 0xb6, 0x63, 0x27, 0xed, 0xee, 0xfc, 0xfd, 0xce, 0xb1, 0xcf, 0x27,
	0xeb, 0x93, 0x60, 0x4f, 0x67, 0xda, 0xf0, 0xe5, 0xe4, 0x36, 0x51, 0x46, 0x91, 0xc0, 0xa9, 0x51,
	0x1f, 0x7a, 0x9f, 0x78, 0xcc, 0x13, 0x31, 0x0b, 0xf9, 0x8f, 0x94, 0x6b, 0x33, 0xfa, 0xed, 0x41,
	0xe7, 0x2a, 0xe2, 0xab, 0xb3, 0x78, 0xae, 0x08, 0x85, 0x76, 0xc4, 0x57, 0x5f, 0xd9, 0x92, 0x53,
	0x6f, 0xe8, 0x8d, 0x77, 0xc3, 0x42, 0x92, 0x03, 0x68, 0x69, 0xc3, 0x0c, 0xa7, 0x3e, 0x72, 0x27,
	0xc8, 0x00, 0x3a, 0x33, 0x76, 0xcb, 0x66, 0xc2, 0x64, 0xb4, 0x31, 0xf4, 0xc6, 0x8d, 0xb0, 0xd4,
	0x84, 0x40, 0x33, 0xd5, 0x3c, 0xa2, 0x4d, 0xe4, 0xf8, 0x8c, 0xcc, 0x08, 0x49, 0x5b, 0x39, 0x33,
	0x42, 0x92, 0x43, 0x08, 0x96, 0x11, 0xd2, 0x00, 0x69, 0xae, 0x2c, 0xd7, 0x53, 0xe4, 0x6d, 0xc7,
	0x9d, 0x1a, 0xfd, 0xf5, 0x01, 0x2e, 0x71, 0x35, 0x68, 0x79, 0x00, 0x9d, 0xef, 0x4a, 0x9b, 0x8a,
	0xe7, 0x52, 0xdb, 0x4f, 0xcc, 0x54, 0x6c, 0xce, 0xa2, 0xdc, 0x75, 0xae, 0x48, 0x0f, 0xfc, 0xc5,
	0x1d, 0x1a, 0xee, 0x84, 0xfe, 0xe2, 0x6e, 0xbd, 0xb8, 0x66, 0x75, 0x71, 0x47, 0xb0, 0xbb, 0x8a,
	0xf8, 0xea, 0x54, 0xa5, 0xb1, 0x41, 0xc7, 0xad, 0x70, 0x0d, 0xc8, 0x0b, 0xe8, 0x5b, 0x71, 0x31,
	0x9f, 0x4b, 0x11, 0x73, 0xd7, 0x14, 0x60, 0xd3, 0x16, 0x27, 0x2f, 0xe1, 0x89, 0x65, 0x21, 0x67,
	0xd1, 0x45, 0x2c, 0x33, 0xd7, 0xdc, 0xc6, 0xe6, 0xed, 0x02, 0x99, 0x42, 0xcb, 0x42, 0x4d, 0x3b,
	0xc3, 0xc6, 0xb8, 0x7b, 0xf2, 0x6c, 0x92, 0xef, 0xe4, 0x7a, 0xd1, 0x13, 0xbb, 0x61, 0xfa, 0x43,
	0x6c, 0x92, 0x2c, 0x74, 0xbd, 0x83, 0x2f, 0x00, 0x6b, 0x48, 0xfa, 0xd0, 0xb8, 0xe1, 0x59, 0xfe,
	0x3f, 0xec, 0x23, 0x39, 0x86, 0xd6, 0x8a, 0xc9, 0xd4, 0xed, 0x5f, 0xf7, 0xa4, 0x5f, 0x7c, 0xb4,
	0xd8, 0xfa, 0xd0, 0x95, 0xdf, 0xf8, 0xaf, 0xbd, 0xd1, 0x2f, 0x0f, 0x0e, 0xdc, 0xb0, 0x4b, 0xc3,
	0x4c, 0xaa, 0x43, 0xae, 0x6f, 0x55, 0xac, 0x39, 0x79, 0x0b, 0x81, 0x46, 0x42, 0x3d, 0xb4, 0x36,
	0xae, 0x5b, 0xab, 0x77, 0x4f, 0x9c, 0x74, 0x2e, 0xf3, 0xf7, 0x06, 0xe7, 0xd0, 0xad, 0xe0, 0x07,
	0x7c, 0x8e, 0xeb, 0x3e, 0xc9, 0xf6, 0xe2, 0xab, 0x4e, 0xff, 0x34, 0xe1, 0x69, 0x3e, 0x3b, 0x5d,
	0x2e, 0x59, 0x92, 0x95, 0x56, 0x9f, 0xc3, 0xbe, 0x51, 0x86, 0xc9, 0xd3, 0x22, 0x9e, 0x1e, 0x86,
	0xa8, 0x0e, 0xed, 0x16, 0x23, 0xf8, 0x66, 0x83, 0xea, 0x63, 0xc7, 0x1a, 0x90, 0x63, 0xe8, 0xa1,
	0x78, 0xb7, 0x62, 0x42, 0xb2, 0x6b, 0xc9, 0xf3, 0x8c, 0x6f, 0x50, 0x1b, 0x05, 0xf7, 0x92, 0x11,
	0x52, 0xdc, 0x33, 0x23, 0x54, 0x8c, 0x49, 0xf2, 0xc3, 0x2d, 0x4e, 0x5e, 0xc1, 0x21, 0xb2, 0xf3,
	0x48, 0xcd, 0xe7, 0x52, 0xb1, 0xa8, 0x34, 0xe8, 0xce, 0xc4, 0x23, 0x55, 0x32, 0x01, 0x52, 0xaf,
	0xa0, 0x65, 0x77, 0x62, 0x1e, 0xa8, 0x94, 0x73, 0x2e, 0xa7, 0x9b, 0x73, 0xda, 0x95, 0x39, 0x5b,
	0xd5, 0x72, 0x4e, 0x59, 0xc1, 0x39, 0x9d, 0xca, 0x9c, 0x5a, 0xa5, 0xfc, 0xcf, 0x57, 0x3c, 0xd1,
	0x42, 0xc5, 0x9a, 0xee, 0x56, 0xfe, 0x73, 0x01, 0xc9, 0x10, 0xba, 0x26, 0x91, 0x6a, 0x71, 0xce,
	0x92, 0x1b, 0x9e, 0x50, 0xc0, 0x9e, 0x2a, 0xc2, 0x7f, 0xb8, 0x96, 0xef, 0xb9, 0x64, 0x19, 0xed,
	0x62, 0xdb, 0x16, 0xb7, 0xb7, 0xc8, 0x22, 0x15, 0x11, 0xdd, 0xc3, 0xd8, 0xe0, 0x33, 0x1e, 0x61,
	0xbe, 0x10, 0x11, 0xdd, 0xcf, 0x8f, 0xb0, 0x15, 0xf6, 0x72, 0x30, 0x62, 0xc9, 0xef, 0x55, 0xcc,
	0x69, 0xcf, 0x5d, 0x0e, 0x85, 0x3e, 0xf9, 0xe9, 0x41, 0xe0, 0xb2, 0x43, 0x3e, 0xc2, 0x5e, 0x35,
	0xc1, 0xe4, 0xb0, 0x48, 0x5d, 0xfd, 0xae, 0x1c, 0x1c, 0xfd, 0x2f, 0xef, 0xa3, 0x1d, 0xf2, 0x19,
	0xf6, 0x6b, 0x69, 0x7c, 0xf4, 0x43, 0x1b, 0x67, 0x7a, 0x23, 0xbc, 0xa3, 0x9d, 0xeb, 0x00, 0xaf,
	0xed, 0xe9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xc9, 0xf7, 0x36, 0xc6, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemClient is the client API for System service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemClient interface {
	SystemStatus(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*SystemStatusResponse, error)
	SystemSummary(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*SystemSummaryResponse, error)
}

type systemClient struct {
	cc *grpc.ClientConn
}

func NewSystemClient(cc *grpc.ClientConn) SystemClient {
	return &systemClient{cc}
}

func (c *systemClient) SystemStatus(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*SystemStatusResponse, error) {
	out := new(SystemStatusResponse)
	err := c.cc.Invoke(ctx, "/system.System/SystemStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) SystemSummary(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*SystemSummaryResponse, error) {
	out := new(SystemSummaryResponse)
	err := c.cc.Invoke(ctx, "/system.System/SystemSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServer is the server API for System service.
type SystemServer interface {
	SystemStatus(context.Context, *GenericRequest) (*SystemStatusResponse, error)
	SystemSummary(context.Context, *GenericRequest) (*SystemSummaryResponse, error)
}

// UnimplementedSystemServer can be embedded to have forward compatible implementations.
type UnimplementedSystemServer struct {
}

func (*UnimplementedSystemServer) SystemStatus(ctx context.Context, req *GenericRequest) (*SystemStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemStatus not implemented")
}
func (*UnimplementedSystemServer) SystemSummary(ctx context.Context, req *GenericRequest) (*SystemSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemSummary not implemented")
}

func RegisterSystemServer(s *grpc.Server, srv SystemServer) {
	s.RegisterService(&_System_serviceDesc, srv)
}

func _System_SystemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).SystemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.System/SystemStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).SystemStatus(ctx, req.(*GenericRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_SystemSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).SystemSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.System/SystemSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).SystemSummary(ctx, req.(*GenericRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _System_serviceDesc = grpc.ServiceDesc{
	ServiceName: "system.System",
	HandlerType: (*SystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SystemStatus",
			Handler:    _System_SystemStatus_Handler,
		},
		{
			MethodName: "SystemSummary",
			Handler:    _System_SystemSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}
